export const surpriseMePrompts = [
  'Prato de Chef: Carpaccio de beterraba com crocante de sementes de abóbora e vinagrete de maracujá',
  'Comida Caseira: Sopa rústica de abóbora com especiarias e croutons de pão integral',
  'Cozinha Molecular: Espuma de alga nori com pérolas de manga e emulsão de limão',
  'Prato de Chef: Ravióli de jaca verde com molho de castanha de caju e manjericão fresco',
  'Comida Caseira: Hambúrguer de cogumelo shiitake com cebola caramelizada e queijo derretido',
  'Prato Rústico: Purê de batata-doce com manteiga de ervas e crocante de sementes de girassol',
  'Cozinha Molecular: Esferificações de suco de beterraba com salada de brotos e molho balsâmico',
  'Prato de Chef: Salmão vegano de melancia grelhada com molho de abacaxi e pimenta rosa',
  'Comida Caseira: Torta de espinafre com queijo vegano e massa crocante',
  'Cozinha Molecular: Espaguete de algas com molho de tomate e crocante de amêndoas',
  'Prato de Chef: Carpaccio de abobrinha com molho de limão siciliano e rúcula selvagem',
  'Comida Caseira: Falafel de grão-de-bico com molho de tahine e salada de pepino',
  'Prato Rústico: Salada tailandesa com camarões e gafanhotos fritos',
  'Cozinha Molecular: Espuma de batata-doce com pó de cogumelos e azeite de trufas',
  'Prato de Chef: Sushi vegano com arroz integral, pepino e manga em fatias finas',
  'Comida Caseira: Espetinho de legumes grelhados com molho de gengibre e alho',
  'Prato Rústico: Guacamole com tortilhas de milho crocantes e pimenta jalapeño',
  'Prato Rústico: Abóbora assada com quinoa, castanhas e molho de laranja',
  'Cozinha Molecular: Esferas de abacate com crocante de amêndoas e vinagrete de limão',
  'Prato de Chef: Creme de ervilha com hortelã fresca e crocante de presunto vegetal',
  'Comida Caseira: Pão de grãos com homus de beterraba e pepino em conserva',
  'Prato Rústico: Berinjela grelhada com molho de tahine e sementes de romã',
  'Cozinha Molecular: Gaspacho de tomate com esferificações de azeite e croutons de pão',
  'Prato de Chef: Tacos vegetarianos com tortilhas de milho, feijão preto e guacamole',
  'Comida Caseira: Salada de grãos com legumes frescos e vinagrete de mostarda',
  'Prato Rústico: Espetinho de legumes com molho de iogurte e ervas aromáticas',
  'Cozinha Molecular: Espuma de couve-flor com pó de cogumelos e crumble de nozes',
  'Prato de Chef: Risoto de aspargos com queijo vegano e raspas de limão siciliano',
  'Comida Caseira: Sopa de lentilha com legumes e temperos aromáticos',
  'Prato Rústico: Cuscuz marroquino com vegetais assados e amêndoas laminadas',
  'Cozinha Molecular: Gelatina de frutas vermelhas com pétalas de rosa comestíveis',
  'Prato de Chef: Espaguete de abobrinha com molho pesto de manjericão e nozes',
  'Comida Caseira: Empadão de palmito com massa crocante e saborosa',
  'Prato Rústico: Salada de grãos com abóbora assada e vinagrete de laranja',
  'Cozinha Molecular: Esferificações de suco de manga com espuma de coco e crocante de amêndoas',
  'Prato de Chef: Salmão vegano de cenoura defumada com molho de maracujá e cebolinha',
  'Comida Caseira: Quiche de espinafre com tofu cremoso e tomates cereja',
  'Prato Rústico: Farofa de castanhas com cebola caramelizada e bananas fritas',
  'Cozinha Molecular: Espuma de manga com crisps de hortelã e calda de maracujá',
  'Prato de Chef: Creme de batata-baroa com crocante de alho-poró e pimenta-do-reino',
  'Comida Caseira: Pão de alho com ervas frescas e azeite de oliva',
  'Prato Rústico: Salada de lentilha com tomate, pepino e folhas verdes',
  'Cozinha Molecular: Gelatina de frutas tropicais com folhas de hortelã e raspas de limão',
  'Prato de Chef: Espaguete de grilos crocantes com molho de tomate e manjericão',
  'Comida Caseira: Salada de folhas verdes com larvas de besouro e vinagrete de limão',
  'Prato Rústico: Grelhado de gafanhotos com legumes da estação e molho de pimenta',
  ];